language: perl
cache:
  - local
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
before_install:
    - "cpanm Carton ExtUtils::MakeMaker"
    - "perl Makefile.PL"
script:
    - "carton install && carton exec -- prove -Ilib t/ xt/"
    - "carton install --cpanfile=cpanfile.compatibility && carton exec -- prove -Ilib t/ xt/"
